create schema Blood_Donation_DB;
use Blood_Donation_DB;
show tables;
describe donar_details;
describe admin_details;
insert into admin_details(admin_name,admin_username,admin_password) values("Raghul","root","demo123");
select * from admin_details;
select * from donar_details;
select * from blood_bank;
select * from campaigns;
select * from blood_quantity;
select* from blood_request;
select * from donation;